name: 7-Zip-zstd

on: [pull_request, workflow_dispatch]

jobs:
  windows-mingw:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows.yml
    with:
      workflow: ${{ github.workflow }}
