name: 7-Zip-zstd

on: [pull_request, workflow_dispatch]

jobs:
  alpine-musl:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}

  windows-mingw:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows-msbuild.yml
    with:
      workflow: ${{ github.workflow }}

  test-windows:
    needs: windows-mingw
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw
