name: _checks

on: [pull_request, workflow_dispatch]

jobs:
  version_tests:
    runs-on: ubuntu-latest
    container: python:3.11.4-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - name: version tests
        run: |
          python -m unittest discover --start-directory .tools --pattern=*_tests.py

  editorconfig:
    runs-on: ubuntu-latest
    container: node:18.16.0-alpine3.18
    steps:
      - uses: actions/checkout@v3
      - run: |
          corepack enable && corepack prepare yarn@3.6.0 --activate
          cd .tools/checks
          yarn install --immutable
          yarn run editorconfig
