on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
      toolset:
        required: false
        type: string
        default: 'gnu'
      version:
        required: false
        type: string
        default: '20.04'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:${{ inputs.version }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - run: |
          glibc_version=2.28
          echo "::group::install GLIBC_$glibc_version from sources"
          apt update && apt install -y gawk bison wget build-essential
          wget -c https://ftp.gnu.org/gnu/glibc/glibc-$glibc_version.tar.gz
          tar -zxvf glibc-$glibc_version.tar.gz && cd glibc-$glibc_version
          mkdir glibc-build && cd glibc-build
          ../configure --prefix=/opt/glibc-$glibc_version
          make
          make install
          echo "::endgroup::"
      - uses: actions/checkout@v4
      - name: build ${{ inputs.workflow }}-ubuntu-${{ inputs.toolset }}
        run: |
          ./${{ inputs.workflow }}/build_${{ inputs.toolset }}.sh

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.toolset }}
          path: ./${{ inputs.workflow }}/release/build-${{ inputs.toolset }}.tar.gz
