name: checks

on: [pull_request, workflow_dispatch]

jobs:
  version_tests:
    runs-on: ubuntu-latest
    container: python:3.11.4-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - name: version tests
        run: |
          python -m unittest discover --start-directory .tools --pattern=*_tests.py

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
      - run: editorconfig-checker
