name: mypy

on: [pull_request, workflow_dispatch]

jobs:
  alpine-musl:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}

  ubuntu-gnu:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}

  windows-msvc:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: msvc

  test-ubuntu-musl:
    needs: alpine-musl
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  test-alpine-musl:
    needs: alpine-musl
    uses: ./.github/workflows/test-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  test-ubuntu-gnu:
    needs: ubuntu-gnu
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-gnu

  test-windows-msvc:
    needs: windows-msvc
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-msvc

  test-nanoserver-msvc:
    needs: windows-msvc
    uses: ./.github/workflows/test-nanoserver.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-msvc

  release:
    needs: [test-alpine-musl, test-ubuntu-musl, test-ubuntu-gnu, test-windows-msvc, test-nanoserver-msvc]
    uses: ./.github/workflows/release.yml
    with:
      workflow: ${{ github.workflow }}
      tool_version: '1.4.1'
      prepare_body: |
        bsdtar -Oxf ./build-musl/build-musl.tar.gz build-musl.md >> body.md
        bsdtar -Oxf ./build-gnu/build-gnu.tar.gz build-gnu.md >> body.md
        bsdtar -Oxf ./build-msvc/build-msvc.tar.gz build-msvc.md >> body.md
      artifacts: ./build-musl/build-musl.tar.gz, ./build-gnu/build-gnu.tar.gz, ./build-msvc/build-msvc.tar.gz
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
