name: pg_dump

on: [pull_request, workflow_dispatch]

jobs:
  prejob:
    uses: ./.github/workflows/set-output-workflow.yml
    with:
      workflow: ${{ github.workflow }}
    secrets:
      _WORKFLOW: ${{ secrets._CURRENT_TOOL }}

  alpine-musl:
    needs: prejob
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}

  alpine-mingw:
    needs: prejob
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: mingw

  ubuntu-glibc-test:
    needs: alpine-musl
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      artifact: build-musl
      test-run: |
        ./${{ github.workflow }} --version

  windows-mingw-test:
    needs: alpine-mingw
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/test-windows.yml
    with:
      artifact: build-mingw
      test-run: |
        ./${{ github.workflow }} --version
