name: pg_dump

on: [pull_request, workflow_dispatch]

jobs:
  prejob:
    uses: ./.github/workflows/set-output-workflow.yml
    with:
      workflow: ${{ github.workflow }}
    secrets:
      _WORKFLOW: ${{ secrets._CURRENT_TOOL }}

  alpine-musl:
    needs: prejob
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}

  alpine-mingw:
    needs: prejob
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: mingw

  alpine-musl-test:
    needs: alpine-musl
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/test-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  ubuntu-glibc-test:
    needs: alpine-musl
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  windows-mingw-test:
    needs: alpine-mingw
    if: ${{ needs.prejob.outputs.workflow == github.workflow }}
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw

  release:
    needs: [ubuntu-glibc-test,
            alpine-musl-test,
            windows-mingw-test]
    uses: ./.github/workflows/release.yml
    with:
      workflow: ${{ github.workflow }}
      tool_version: '15.0'
      prepare_body: |
        bsdtar -Oxf ./build-musl/build-musl.tar.gz build-musl.md >> body.md
        bsdtar -Oxf ./build-mingw/build-mingw.tar.gz build-mingw.md >> body.md
      artifacts: ./build-musl/build-musl.tar.gz,./build-mingw/build-mingw.tar.gz
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
