name: playwright
# version_tests: skip_readme

on: [pull_request, workflow_dispatch]

jobs:
  ubuntu-gnu:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: gnu

  windows-msvc:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: msvc

  test-ubuntu:
    needs: ubuntu-gnu
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-gnu

  test-windows-msvc:
    needs: windows-msvc
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-msvc

  release:
    needs: [test-windows-msvc, test-ubuntu]
    uses: ./.github/workflows/release.yml
    with:
      workflow: ${{ github.workflow }}
      tool_version: '1.35.0'
      prepare_body: |
        bsdtar -Oxf ./build-gnu/build-gnu.tar.gz build-gnu.md >> body.md
        bsdtar -Oxf ./build-msvc/build-msvc.tar.gz build-msvc.md >> body.md
      artifacts: ./build-msvc/build-msvc.tar.gz, ./build-gnu/build-gnu.tar.gz
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
