name: redis

on: [pull_request, workflow_dispatch]

jobs:
  alpine-musl:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      toolset: musl
      version: 3.16

  alpine-musl-test:
    needs: alpine-musl
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/test-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl
