on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
      artifact:
        required: true
        type: string
      version:
        required: false
        type: string
        default: 'latest'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:${{ inputs.version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: .

      - name: Test ${{ inputs.artifact }} build on ubuntu:${{ inputs.version }}
        run: |
          tar -xf ./${{ inputs.artifact }}.tar.gz -C ./bin
          cd ./${{ inputs.workflow }}
          ./test_linux.sh

