on:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
      artifact:
        required: true
        type: string
      version:
        required: false
        type: string
        default: 'latest'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [
          "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "ubuntu:latest"
          "fedora:35", "fedora:36", "fedora:37", "fedora:latest",
          "rockylinux:8-minimal", "rockylinux:9-minimal", "rockylinux:latest"
        ]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: .

      - name: Test ${{ inputs.artifact }} build on ${{ matrix.container }}
        run: |
          tar -xf ./${{ inputs.artifact }}.tar.gz -C ./bin
          cd ./${{ inputs.workflow }}
          ./test_linux.sh

