name: zstd

on: [pull_request, workflow_dispatch]

jobs:
  alpine-musl:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-alpine.yml
    with:
      workflow: ${{ github.workflow }}

  test-alpine:
    needs: alpine-musl
    uses: ./.github/workflows/test-alpine.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  test-ubuntu:
    needs: alpine-musl
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-musl

  windows-mingw:
    if: ${{ vars.CURRENT_TOOL == github.workflow }}
    uses: ./.github/workflows/build-windows-msys2.yml
    with:
      workflow: ${{ github.workflow }}
      msys2_install: make git mingw-w64-x86_64-gcc
      toolset: mingw

  test-windows:
    needs: windows-mingw
    uses: ./.github/workflows/test-windows.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw

  test-nanoserver:
    needs: windows-mingw
    uses: ./.github/workflows/test-nanoserver.yml
    with:
      workflow: ${{ github.workflow }}
      artifact: build-mingw
